platform :ios, '13.0'
use_frameworks!
use_modular_headers!

flutter_application_path = File.expand_path(File.join('..', '..'), __FILE__)
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
